# GoReleaser configuration
version: 2

project_name: opsql

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: opsql
    binary: opsql
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/pyama86/opsql/cmd.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: opsql
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - examples/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: pyama86
    name: opsql
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## opsql {{ .Version }}

    This release includes the following changes:
  footer: |
    ## Docker Images

    Docker images are available at:
    - `ghcr.io/pyama86/opsql:{{ .Version }}`
    - `ghcr.io/pyama86/opsql:latest`

    ## Installation

    ### Binary
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker pull ghcr.io/pyama86/opsql:{{ .Version }}
    ```

    ### Go Install
    ```bash
    go install github.com/pyama86/opsql@{{ .Version }}
    ```

  name_template: "Release {{ .Version }}"
